name: convenient_dev_toolkit
description: 便捷工具包
version: 0.2.2
homepage: https://github.com/aleiin/convenient_dev_toolkit

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  decimal: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


