name: convenient_dev_toolkit
description: 便捷工具包
version: 0.3.0
homepage: https://github.com/aleiin/convenient_dev_toolkit

# flutter版本: 3.24.9
environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  decimal: ^3.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


