## .github/workflows/publish.yml
#name: Publish to pub.dev
#
#on:
#  push:
#    tags:
#      - 'v[0-9]+.[0-9]+.[0-9]+*' # tag pattern on pub.dev: 'v{{version}'
#
#jobs:
#  publishing:
#    runs-on: ubuntu-latest
#    steps:
#      # 拉取仓库代码
#      - name: "Checkout"
#        uses: actions/checkout@v3
#      # 发布插件
#      - name: Dart and Flutter Package Publisher
#        uses: k-paxian/dart-package-publisher@master
#        with:
#          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
#          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
#          suppressBuildRunner: true
#          flutter: true
#          skipTests: true
#          force: true

name: Publish to Pub.dev

on: push

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main # required!

      - name: '>> Dart package <<'
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}